
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

COMMENT ON SCHEMA "public" IS 'standard public schema';

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."Company" (
    "id" bigint NOT NULL,
    "auth_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "logo_path" "text",
    "name" "text" NOT NULL,
    "company_number" "text" NOT NULL,
    "address" "text" NOT NULL,
    "phone_number" "text",
    "email" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."Company" OWNER TO "postgres";

ALTER TABLE "public"."Company" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Company_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."Council Application" (
    "id" bigint NOT NULL,
    "auth_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "taxi_id" bigint NOT NULL,
    "document_path" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."Council Application" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."Council Application Receipt" (
    "id" bigint NOT NULL,
    "auth_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "taxi_id" bigint NOT NULL,
    "document_path" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."Council Application Receipt" OWNER TO "postgres";

ALTER TABLE "public"."Council Application Receipt" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Council Application Receipt_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE "public"."Council Application" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Council Application_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."Driver" (
    "id" bigint NOT NULL,
    "auth_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "picture_path" "text",
    "first_names" "text" NOT NULL,
    "last_name" "text" NOT NULL,
    "phone_number" "text",
    "email" "text",
    "date_of_birth" "date",
    "national_insurance_number" "text",
    "is_retired" boolean DEFAULT false NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "active_hire_agreement_id" bigint,
    "active_insurance_id" bigint,
    "active_drivers_licence_id" bigint,
    "active_drivers_taxi_badge_id" bigint
);

ALTER TABLE "public"."Driver" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."Driver Application" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "company_id" bigint NOT NULL,
    "picture_path" "text",
    "first_names" "text",
    "last_name" "text",
    "phone_number" "text",
    "email" "text",
    "date_of_birth" "date",
    "national_insurance_number" "text",
    "drivers_licence_path" "text",
    "drivers_licence_number" "text" NOT NULL,
    "drivers_licence_start_date" "date" NOT NULL,
    "drivers_licence_end_date" "date" NOT NULL,
    "taxi_badge_path" "text",
    "taxi_badge_number" "text" NOT NULL,
    "taxi_badge_start_date" "date" NOT NULL,
    "taxi_badge_end_date" "date" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."Driver Application" OWNER TO "postgres";

ALTER TABLE "public"."Driver" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Driver_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."Drivers Licence" (
    "id" bigint NOT NULL,
    "auth_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "driver_id" bigint NOT NULL,
    "document_path" "text",
    "licence_number" "text" NOT NULL,
    "start_date" "date" NOT NULL,
    "end_date" "date" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."Drivers Licence" OWNER TO "postgres";

ALTER TABLE "public"."Drivers Licence" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Drivers Licence_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."Drivers Taxi Badge" (
    "id" bigint NOT NULL,
    "auth_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "driver_id" bigint NOT NULL,
    "document_path" "text",
    "badge_number" "text" NOT NULL,
    "start_date" "date",
    "end_date" "date" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."Drivers Taxi Badge" OWNER TO "postgres";

ALTER TABLE "public"."Drivers Taxi Badge" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Drivers Taxi Badge_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."Employee" (
    "id" bigint NOT NULL,
    "auth_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "company_id" bigint NOT NULL,
    "picture_path" "text",
    "first_names" "text" NOT NULL,
    "last_name" "text" NOT NULL,
    "phone_number" "text",
    "email" "text" NOT NULL,
    "date_of_birth" "date" NOT NULL,
    "national_insurance_number" "text" NOT NULL,
    "signature_path" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."Employee" OWNER TO "postgres";

ALTER TABLE "public"."Employee" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Employee_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."Hire Agreement" (
    "id" bigint NOT NULL,
    "auth_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "taxi_id" bigint NOT NULL,
    "driver_id" bigint NOT NULL,
    "permission_letter_document_path" "text",
    "contract_document_path" "text",
    "start_date" "date" NOT NULL,
    "end_date" "date",
    "rent_amount" numeric(12,2) NOT NULL,
    "deposit_amount" numeric(12,2) NOT NULL,
    "deposit_receipt_document_path" "text",
    "is_retired" boolean DEFAULT false NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."Hire Agreement" OWNER TO "postgres";

ALTER TABLE "public"."Hire Agreement" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Hire Agreement_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."Insurance" (
    "id" bigint NOT NULL,
    "auth_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "taxi_id" bigint NOT NULL,
    "driver_id" bigint,
    "document_path" "text",
    "policy_number" "text" NOT NULL,
    "is_any_driver" boolean NOT NULL,
    "start_date" "date" NOT NULL,
    "end_date" "date" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."Insurance" OWNER TO "postgres";

ALTER TABLE "public"."Insurance" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Insurance_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."Picture" (
    "id" bigint NOT NULL,
    "auth_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "hire_id" bigint NOT NULL,
    "picture_path" "text" NOT NULL,
    "is_before_hire" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."Picture" OWNER TO "postgres";

ALTER TABLE "public"."Picture" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Picture_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."Rent" (
    "id" bigint NOT NULL,
    "auth_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "hire_id" bigint NOT NULL,
    "receipt_document_path" "text",
    "start_date" "date" NOT NULL,
    "end_date" "date" NOT NULL,
    "amount" numeric(12,2) NOT NULL,
    "is_paid" boolean DEFAULT false NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."Rent" OWNER TO "postgres";

ALTER TABLE "public"."Rent" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Rent_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."Taxi" (
    "id" bigint NOT NULL,
    "auth_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "picture_path" "text",
    "logbook_document_path" "text",
    "number_plate" "text" NOT NULL,
    "colour" "text" NOT NULL,
    "chassis_number" "text" NOT NULL,
    "registration_date" "date",
    "expected_expiry_date" "date",
    "road_tax_expiry_date" "date",
    "is_retired" boolean DEFAULT false NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "vehicle_id" bigint NOT NULL,
    "active_hire_agreement_id" bigint,
    "active_insurance_id" bigint,
    "active_taxi_licence_id" bigint
);

ALTER TABLE "public"."Taxi" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."Taxi Licence" (
    "id" bigint NOT NULL,
    "auth_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "taxi_id" bigint NOT NULL,
    "compliance_certificate_document_path" "text",
    "compliance_certificate_licence_number" "text" NOT NULL,
    "phc_licence_document_path" "text",
    "phc_number" "text" NOT NULL,
    "start_date" "date",
    "end_date" "date" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."Taxi Licence" OWNER TO "postgres";

ALTER TABLE "public"."Taxi Licence" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Taxi Licence_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE "public"."Taxi" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Taxi_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."Vehicle" (
    "id" bigint NOT NULL,
    "auth_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "make" "text" NOT NULL,
    "model" "text" NOT NULL,
    "cc" smallint,
    "fuel_type" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."Vehicle" OWNER TO "postgres";

ALTER TABLE "public"."Vehicle" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Vehicle_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."Company"
    ADD CONSTRAINT "company_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."Council Application"
    ADD CONSTRAINT "council_application_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."Council Application Receipt"
    ADD CONSTRAINT "council_application_receipt_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."Driver Application"
    ADD CONSTRAINT "driver_application_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."Driver"
    ADD CONSTRAINT "driver_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."Drivers Licence"
    ADD CONSTRAINT "drivers_licence_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."Drivers Taxi Badge"
    ADD CONSTRAINT "drivers_taxi_badge_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."Employee"
    ADD CONSTRAINT "employee_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."Hire Agreement"
    ADD CONSTRAINT "hire_agreement_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."Insurance"
    ADD CONSTRAINT "insurance_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."Picture"
    ADD CONSTRAINT "picture_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."Rent"
    ADD CONSTRAINT "rent_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."Taxi Licence"
    ADD CONSTRAINT "taxi_licence_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."Taxi"
    ADD CONSTRAINT "taxi_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."Vehicle"
    ADD CONSTRAINT "vehicle_pkey" PRIMARY KEY ("id");

CREATE INDEX "company_auth_id_index" ON "public"."Company" USING "btree" ("auth_id");

CREATE INDEX "council_application_auth_id_index" ON "public"."Council Application" USING "btree" ("auth_id");

CREATE INDEX "council_application_receipt_auth_id_index" ON "public"."Council Application Receipt" USING "btree" ("auth_id");

CREATE INDEX "council_application_receipt_taxi_id_index" ON "public"."Council Application Receipt" USING "btree" ("taxi_id");

CREATE INDEX "council_application_taxi_id_index" ON "public"."Council Application" USING "btree" ("taxi_id");

CREATE INDEX "driver_auth_id_index" ON "public"."Driver" USING "btree" ("auth_id");

CREATE INDEX "drivers_licence_auth_id_index" ON "public"."Drivers Licence" USING "btree" ("auth_id");

CREATE INDEX "drivers_licence_driver_id_index" ON "public"."Drivers Licence" USING "btree" ("driver_id");

CREATE INDEX "drivers_taxi_badge_auth_id_index" ON "public"."Drivers Taxi Badge" USING "btree" ("auth_id");

CREATE INDEX "drivers_taxi_badge_driver_id_index" ON "public"."Drivers Taxi Badge" USING "btree" ("driver_id");

CREATE INDEX "employee_auth_id_index" ON "public"."Employee" USING "btree" ("auth_id");

CREATE INDEX "hire_agreement_auth_id_index" ON "public"."Hire Agreement" USING "btree" ("auth_id");

CREATE INDEX "hire_agreement_driver_id_index" ON "public"."Hire Agreement" USING "btree" ("driver_id");

CREATE INDEX "hire_agreement_taxi_id_index" ON "public"."Hire Agreement" USING "btree" ("taxi_id");

CREATE INDEX "insurance_auth_id_index" ON "public"."Insurance" USING "btree" ("auth_id");

CREATE INDEX "insurance_driver_id_index" ON "public"."Insurance" USING "btree" ("driver_id");

CREATE INDEX "insurance_taxi_id_index" ON "public"."Insurance" USING "btree" ("taxi_id");

CREATE INDEX "picture_auth_id_index" ON "public"."Picture" USING "btree" ("auth_id");

CREATE INDEX "picture_hire_id_index" ON "public"."Picture" USING "btree" ("hire_id");

CREATE INDEX "rent_auth_id_index" ON "public"."Rent" USING "btree" ("auth_id");

CREATE INDEX "rent_hire_id_index" ON "public"."Rent" USING "btree" ("hire_id");

CREATE INDEX "taxi_auth_id_index" ON "public"."Taxi" USING "btree" ("auth_id");

CREATE INDEX "taxi_licence_auth_id_index" ON "public"."Taxi Licence" USING "btree" ("auth_id");

CREATE INDEX "taxi_licence_taxi_id_index" ON "public"."Taxi Licence" USING "btree" ("taxi_id");

CREATE INDEX "vehicle_auth_id_index" ON "public"."Vehicle" USING "btree" ("auth_id");

ALTER TABLE ONLY "public"."Company"
    ADD CONSTRAINT "company_auth_id_fkey" FOREIGN KEY ("auth_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."Council Application"
    ADD CONSTRAINT "council_application_auth_id_fkey" FOREIGN KEY ("auth_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."Council Application Receipt"
    ADD CONSTRAINT "council_application_receipt_auth_id_fkey" FOREIGN KEY ("auth_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."Council Application Receipt"
    ADD CONSTRAINT "council_application_receipt_taxi_id_fkey" FOREIGN KEY ("taxi_id") REFERENCES "public"."Taxi"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."Council Application"
    ADD CONSTRAINT "council_application_taxi_id_fkey" FOREIGN KEY ("taxi_id") REFERENCES "public"."Taxi"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."Driver"
    ADD CONSTRAINT "driver_active_drivers_licence_id_fkey" FOREIGN KEY ("active_drivers_licence_id") REFERENCES "public"."Drivers Licence"("id") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY "public"."Driver"
    ADD CONSTRAINT "driver_active_drivers_taxi_badge_id_fkey" FOREIGN KEY ("active_drivers_taxi_badge_id") REFERENCES "public"."Drivers Taxi Badge"("id") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY "public"."Driver"
    ADD CONSTRAINT "driver_active_hire_agreement_id_fkey" FOREIGN KEY ("active_hire_agreement_id") REFERENCES "public"."Hire Agreement"("id") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY "public"."Driver"
    ADD CONSTRAINT "driver_active_insurance_id_fkey" FOREIGN KEY ("active_insurance_id") REFERENCES "public"."Insurance"("id") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY "public"."Driver Application"
    ADD CONSTRAINT "driver_application_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "public"."Company"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."Driver"
    ADD CONSTRAINT "driver_auth_id_fkey" FOREIGN KEY ("auth_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."Drivers Licence"
    ADD CONSTRAINT "drivers_licence_auth_id_fkey" FOREIGN KEY ("auth_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."Drivers Licence"
    ADD CONSTRAINT "drivers_licence_driver_id_fkey" FOREIGN KEY ("driver_id") REFERENCES "public"."Driver"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."Drivers Taxi Badge"
    ADD CONSTRAINT "drivers_taxi_badge_auth_id_fkey" FOREIGN KEY ("auth_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."Drivers Taxi Badge"
    ADD CONSTRAINT "drivers_taxi_badge_driver_id_fkey" FOREIGN KEY ("driver_id") REFERENCES "public"."Driver"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."Employee"
    ADD CONSTRAINT "employee_auth_id_fkey" FOREIGN KEY ("auth_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."Employee"
    ADD CONSTRAINT "employee_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "public"."Company"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."Hire Agreement"
    ADD CONSTRAINT "hire_agreement_auth_id_fkey" FOREIGN KEY ("auth_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."Hire Agreement"
    ADD CONSTRAINT "hire_agreement_driver_id_fkey" FOREIGN KEY ("driver_id") REFERENCES "public"."Driver"("id") ON UPDATE CASCADE;

ALTER TABLE ONLY "public"."Hire Agreement"
    ADD CONSTRAINT "hire_agreement_taxi_id_fkey" FOREIGN KEY ("taxi_id") REFERENCES "public"."Taxi"("id") ON UPDATE CASCADE;

ALTER TABLE ONLY "public"."Insurance"
    ADD CONSTRAINT "insurance_auth_id_fkey" FOREIGN KEY ("auth_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."Insurance"
    ADD CONSTRAINT "insurance_driver_id_fkey" FOREIGN KEY ("driver_id") REFERENCES "public"."Driver"("id") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY "public"."Insurance"
    ADD CONSTRAINT "insurance_taxi_id_fkey" FOREIGN KEY ("taxi_id") REFERENCES "public"."Taxi"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."Picture"
    ADD CONSTRAINT "picture_auth_id_fkey" FOREIGN KEY ("auth_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."Picture"
    ADD CONSTRAINT "picture_hire_id_fkey" FOREIGN KEY ("hire_id") REFERENCES "public"."Hire Agreement"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."Rent"
    ADD CONSTRAINT "rent_auth_id_fkey" FOREIGN KEY ("auth_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."Rent"
    ADD CONSTRAINT "rent_hire_id_fkey" FOREIGN KEY ("hire_id") REFERENCES "public"."Hire Agreement"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."Taxi"
    ADD CONSTRAINT "taxi_active_hire_agreement_id_fkey" FOREIGN KEY ("active_hire_agreement_id") REFERENCES "public"."Hire Agreement"("id") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY "public"."Taxi"
    ADD CONSTRAINT "taxi_active_insurance_id_fkey" FOREIGN KEY ("active_insurance_id") REFERENCES "public"."Insurance"("id") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY "public"."Taxi"
    ADD CONSTRAINT "taxi_active_taxi_licence_id_fkey" FOREIGN KEY ("active_taxi_licence_id") REFERENCES "public"."Taxi Licence"("id") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY "public"."Taxi"
    ADD CONSTRAINT "taxi_auth_id_fkey" FOREIGN KEY ("auth_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."Taxi Licence"
    ADD CONSTRAINT "taxi_licence_auth_id_fkey" FOREIGN KEY ("auth_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."Taxi Licence"
    ADD CONSTRAINT "taxi_licence_taxi_id_fkey" FOREIGN KEY ("taxi_id") REFERENCES "public"."Taxi"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."Taxi"
    ADD CONSTRAINT "taxi_vehicle_id_fkey" FOREIGN KEY ("vehicle_id") REFERENCES "public"."Vehicle"("id") ON UPDATE CASCADE;

ALTER TABLE ONLY "public"."Vehicle"
    ADD CONSTRAINT "vehiclee_auth_id_fkey" FOREIGN KEY ("auth_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."Company" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."Council Application" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."Council Application Receipt" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."Driver" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."Driver Application" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Driver applications can be viewed by anyone as long as they hav" ON "public"."Driver Application" TO "authenticated", "anon" USING (true);

ALTER TABLE "public"."Drivers Licence" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."Drivers Taxi Badge" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."Employee" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all functionality for users based on auth_id" ON "public"."Company" TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "auth_id")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "auth_id"));

CREATE POLICY "Enable all functionality for users based on auth_id" ON "public"."Council Application" TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "auth_id")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "auth_id"));

CREATE POLICY "Enable all functionality for users based on auth_id" ON "public"."Council Application Receipt" TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "auth_id")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "auth_id"));

CREATE POLICY "Enable all functionality for users based on auth_id" ON "public"."Driver" TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "auth_id")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "auth_id"));

CREATE POLICY "Enable all functionality for users based on auth_id" ON "public"."Drivers Licence" TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "auth_id")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "auth_id"));

CREATE POLICY "Enable all functionality for users based on auth_id" ON "public"."Drivers Taxi Badge" TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "auth_id")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "auth_id"));

CREATE POLICY "Enable all functionality for users based on auth_id" ON "public"."Employee" TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "auth_id")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "auth_id"));

CREATE POLICY "Enable all functionality for users based on auth_id" ON "public"."Hire Agreement" TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "auth_id")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "auth_id"));

CREATE POLICY "Enable all functionality for users based on auth_id" ON "public"."Insurance" TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "auth_id")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "auth_id"));

CREATE POLICY "Enable all functionality for users based on auth_id" ON "public"."Picture" TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "auth_id")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "auth_id"));

CREATE POLICY "Enable all functionality for users based on auth_id" ON "public"."Rent" TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "auth_id")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "auth_id"));

CREATE POLICY "Enable all functionality for users based on auth_id" ON "public"."Taxi" TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "auth_id")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "auth_id"));

CREATE POLICY "Enable all functionality for users based on auth_id" ON "public"."Taxi Licence" TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "auth_id")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "auth_id"));

CREATE POLICY "Enable all functionality for users based on auth_id" ON "public"."Vehicle" TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "auth_id")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "auth_id"));

ALTER TABLE "public"."Hire Agreement" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."Insurance" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."Picture" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."Rent" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."Taxi" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."Taxi Licence" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."Vehicle" ENABLE ROW LEVEL SECURITY;

ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON TABLE "public"."Company" TO "anon";
GRANT ALL ON TABLE "public"."Company" TO "authenticated";
GRANT ALL ON TABLE "public"."Company" TO "service_role";

GRANT ALL ON SEQUENCE "public"."Company_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Company_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Company_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."Council Application" TO "anon";
GRANT ALL ON TABLE "public"."Council Application" TO "authenticated";
GRANT ALL ON TABLE "public"."Council Application" TO "service_role";

GRANT ALL ON TABLE "public"."Council Application Receipt" TO "anon";
GRANT ALL ON TABLE "public"."Council Application Receipt" TO "authenticated";
GRANT ALL ON TABLE "public"."Council Application Receipt" TO "service_role";

GRANT ALL ON SEQUENCE "public"."Council Application Receipt_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Council Application Receipt_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Council Application Receipt_id_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."Council Application_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Council Application_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Council Application_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."Driver" TO "anon";
GRANT ALL ON TABLE "public"."Driver" TO "authenticated";
GRANT ALL ON TABLE "public"."Driver" TO "service_role";

GRANT ALL ON TABLE "public"."Driver Application" TO "anon";
GRANT ALL ON TABLE "public"."Driver Application" TO "authenticated";
GRANT ALL ON TABLE "public"."Driver Application" TO "service_role";

GRANT ALL ON SEQUENCE "public"."Driver_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Driver_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Driver_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."Drivers Licence" TO "anon";
GRANT ALL ON TABLE "public"."Drivers Licence" TO "authenticated";
GRANT ALL ON TABLE "public"."Drivers Licence" TO "service_role";

GRANT ALL ON SEQUENCE "public"."Drivers Licence_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Drivers Licence_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Drivers Licence_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."Drivers Taxi Badge" TO "anon";
GRANT ALL ON TABLE "public"."Drivers Taxi Badge" TO "authenticated";
GRANT ALL ON TABLE "public"."Drivers Taxi Badge" TO "service_role";

GRANT ALL ON SEQUENCE "public"."Drivers Taxi Badge_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Drivers Taxi Badge_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Drivers Taxi Badge_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."Employee" TO "anon";
GRANT ALL ON TABLE "public"."Employee" TO "authenticated";
GRANT ALL ON TABLE "public"."Employee" TO "service_role";

GRANT ALL ON SEQUENCE "public"."Employee_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Employee_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Employee_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."Hire Agreement" TO "anon";
GRANT ALL ON TABLE "public"."Hire Agreement" TO "authenticated";
GRANT ALL ON TABLE "public"."Hire Agreement" TO "service_role";

GRANT ALL ON SEQUENCE "public"."Hire Agreement_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Hire Agreement_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Hire Agreement_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."Insurance" TO "anon";
GRANT ALL ON TABLE "public"."Insurance" TO "authenticated";
GRANT ALL ON TABLE "public"."Insurance" TO "service_role";

GRANT ALL ON SEQUENCE "public"."Insurance_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Insurance_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Insurance_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."Picture" TO "anon";
GRANT ALL ON TABLE "public"."Picture" TO "authenticated";
GRANT ALL ON TABLE "public"."Picture" TO "service_role";

GRANT ALL ON SEQUENCE "public"."Picture_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Picture_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Picture_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."Rent" TO "anon";
GRANT ALL ON TABLE "public"."Rent" TO "authenticated";
GRANT ALL ON TABLE "public"."Rent" TO "service_role";

GRANT ALL ON SEQUENCE "public"."Rent_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Rent_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Rent_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."Taxi" TO "anon";
GRANT ALL ON TABLE "public"."Taxi" TO "authenticated";
GRANT ALL ON TABLE "public"."Taxi" TO "service_role";

GRANT ALL ON TABLE "public"."Taxi Licence" TO "anon";
GRANT ALL ON TABLE "public"."Taxi Licence" TO "authenticated";
GRANT ALL ON TABLE "public"."Taxi Licence" TO "service_role";

GRANT ALL ON SEQUENCE "public"."Taxi Licence_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Taxi Licence_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Taxi Licence_id_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."Taxi_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Taxi_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Taxi_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."Vehicle" TO "anon";
GRANT ALL ON TABLE "public"."Vehicle" TO "authenticated";
GRANT ALL ON TABLE "public"."Vehicle" TO "service_role";

GRANT ALL ON SEQUENCE "public"."Vehicle_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Vehicle_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Vehicle_id_seq" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
